# Generated by Django 5.2.6 on 2025-09-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Stock',
            new_name='Stok',
        ),
    ]
