# Generated by Django 5.2.6 on 2025-09-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_stock_car_stok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Stok',
            new_name='stok',
        ),
    ]
