# Generated by Django 5.2.6 on 2025-09-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_brand_car_brand_rename_name_car_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
